parameters:
    tuck_converter.config_format_converter.class: Tuck\ConverterBundle\ConfigFormatConverter
    tuck_converter.dumper.factory.class: Tuck\ConverterBundle\Dumper\DumperFactory
    tuck_converter.loader.factory.class: Tuck\ConverterBundle\Loader\LoaderFactory

services:
    tuck_converter.config_format_converter:
        class: %tuck_converter.config_format_converter.class%
        arguments: ['@tuck_converter.loader.factory', '@tuck_converter.dumper.factory']
    tuck_converter.dumper.factory:
        class: %tuck_converter.dumper.factory.class%
    tuck_converter.loader.factory:
        class: %tuck_converter.loader.factory.class%
